### ISSUE TITLE
[Feature Request] Prefers Reduced Motion

### ISSUE THREAD

**Issue by goatandsheep** [airbnb/lottie-web#1986]
We should be inclusive to those who [prefer reduced motion](https://developers.google.com/web/updates/2019/03/prefers-reduced-motion), including those who are prone to motion sickness or are epileptic by adding CSS classes to reduce animations where there is a `prefers-reduced-motion` media query. The article uses the following code snippet as an example of how it could look:

```css
/*
  If the user has expressed their preference for
  reduced motion, then don't use animations on buttons.
*/
@media (prefers-reduced-motion: reduce) {
  button {
    animation: none;
  }
}
```
