### ISSUE TITLE
Strange flash, fade going to black on first render

### ISSUE THREAD

**Issue by numito** [airbnb/lottie-web#2211]
**Tell us about your environment**
Javascript Lottie web player. Lottie animation is played frame by frame based on scroll position, using GotoAntStop.
You can see the animation on:
https://amadeus.dfacto.ch
Login: amadeus
Password: p4amadeus

* **Browser and Browser Version:**
All

* **After Effects Version:**
2019

**What did you do? Please explain the steps you took before you encountered the problem.**
The animation plays fine, but there is strange black flash when fading to blue color. I can't figure out if it's a browser bug, an animation bug or a bug from my code. It only the first time you play the animation or you scroll, if you replay or scroll up and down this behaviour disappear. 

**What did you expect to happen?**
The animation to play without the black flicker

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, you have some transition properties applied to all svg elements that are producing those tweens between color.
```css
svg path, svg circle, svg rect, svg polygon {
    -webkit-transition: fill 0.3s linear 0s;
    -moz-transition: fill 0.3s linear 0s;
    transition: fill 0.3s linear 0s;
}
```
